### PR TITLE
[hotfix] Fix wait_for_selector to work

### LINKED ISSUE #78: wait_for_selector is not working
### Step To Reproduce / Observed behavior

```
  page.goto("https://twitter.com/#{username}")
  page.wait_for_selector("article")
```

puppeteer-ruby with revision: `537bc549311f333aad6481e44e698423674c1e59` works well.
Current main branch is broken... (TimeoutError)

### Expected behavior

wait_for_selector passes after `article` is found.

### Environment

```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
```

### PR DESCRIPTION
**Pull request by YusukeIwaki**
resolves #78

### CODE REVIEW

File: lib/puppeteer/wait_task.rb [hunk 1]
```diff
@@ -135,10 +135,9 @@ def rerun
       /**
        * @return {!Promise<*>}
        */
-      function pollMutation() {
-          const success = predicate(...args);
```
Comment (YusukeIwaki) [inline lib/puppeteer/wait_task.rb:139]: `predicate` can be a Promise, and success was always true... :(
